tier1 always be None in GET tier config request for level 2
Without having null allowable SDk will throw the following error  
TypeError: Invalid structure for initialization of `TierConfigRequest`. 
Error: {0: {'tiers': {'tier1': ['Field may not be null.']}}, 1: {'tiers': {'tier1': ['Field may not be null.']}}}.

Because in t2 config request t1 account always be none as per api result from connect platform